[smtp]
server   = "smtp.gmail.com"         # 或你邮箱服务商的 SMTP 地址
port     = 587                      # TLS 常用端口
user     = "lixuanxiner@gmail.com"  # 你的完整邮箱
password = "iwmz umci jsdy tjxp"    # 两步验证后生成的应用专用密码


